In [20]:
import pandas as pd
import numpy as np

In [21]:
housing_df = pd.read_csv('house_train_raw.csv')

In [24]:
housing_df.describe()

Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000   
mean    730.500000    56.897260    70.049958   10516.828082     6.099315   
std     421.610009    42.300571    24.284752    9981.264932     1.382997   
min       1.000000    20.000000    21.000000    1300.000000     1.000000   
25%     365.750000    20.000000    59.000000    7553.500000     5.000000   
50%     730.500000    50.000000    69.000000    9478.500000     6.000000   
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000   
max    1460.000000   190.000000   313.000000  215245.000000    10.000000   

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  ...  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000  ...   
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726  ...   
std       1.112799    30.202904     20.645407   181.066207   456.098091  ...   
min       1.000000  1872.000000   1950.000000     0.000000     0.000000  ...   
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000  ...   
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000  ...   
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000  ...   
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000  ...   

        WoodDeckSF  OpenPorchSF  EnclosedPorch    3SsnPorch  ScreenPorch  \
count  1460.000000  1460.000000    1460.000000  1460.000000  1460.000000   
mean     94.244521    46.660274      21.954110     3.409589    15.060959   
std     125.338794    66.256028      61.119149    29.317331    55.757415   
min       0.000000     0.000000       0.000000     0.000000     0.000000   
25%       0.000000     0.000000       0.000000     0.000000     0.000000   
50%       0.000000    25.000000       0.000000     0.000000     0.000000   
75%     168.000000    68.000000       0.000000     0.000000     0.000000   
max     857.000000   547.000000     552.000000   508.000000   480.000000   

          PoolArea       MiscVal       MoSold       YrSold      SalePrice  
count  1460.000000   1460.000000  1460.000000  1460.000000    1460.000000  
mean      2.758904     43.489041     6.321918  2007.815753  180921.195890  
std      40.177307    496.123024     2.703626     1.328095   79442.502883  
min       0.000000      0.000000     1.000000  2006.000000   34900.000000  
25%       0.000000      0.000000     5.000000  2007.000000  129975.000000  
50%       0.000000      0.000000     6.000000  2008.000000  163000.000000  
75%       0.000000      0.000000     8.000000  2009.000000  214000.000000  
max     738.000000  15500.000000    12.000000  2010.000000  755000.000000  

[8 rows x 38 columns]

In [26]:
housing_df.isna().sum().sort_values(ascending=False)

PoolQC         1453
MiscFeature    1406
Alley          1369
Fence          1179
FireplaceQu     690
               ... 
ExterQual         0
Exterior2nd       0
Exterior1st       0
RoofMatl          0
SalePrice         0
Length: 81, dtype: int64

In [ ]:
## Predecimos los precios de las casas. 

In [27]:
housing_df['SalePrice']

0       208500
1       181500
2       223500
3       140000
4       250000
         ...  
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [28]:
housing_df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive

In [44]:
(housing_df.dtypes == 'int64').sort_values()

HeatingQC       False
MasVnrArea      False
ExterQual       False
Functional      False
Foundation      False
                ...  
HalfBath         True
BedroomAbvGr     True
KitchenAbvGr     True
1stFlrSF         True
SalePrice        True
Length: 81, dtype: bool

In [45]:
housing_df['SaleCondition']

0        Normal
1        Normal
2        Normal
3       Abnorml
4        Normal
         ...   
1455     Normal
1456     Normal
1457     Normal
1458     Normal
1459     Normal
Name: SaleCondition, Length: 1460, dtype: object

In [46]:
housing_df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

## Definición de X

In [53]:
housing_df['OverallQual'].unique()

array([ 7,  6,  8,  5,  9,  4, 10,  3,  1,  2], dtype=int64)

In [55]:
housing_df['FullBath'].unique()

array([2, 1, 3, 0], dtype=int64)

In [57]:
housing_df['KitchenAbvGr'].unique()

array([1, 2, 3, 0], dtype=int64)

In [59]:
housing_df['BedroomAbvGr'].unique()

array([3, 4, 1, 2, 0, 5, 6, 8], dtype=int64)

In [62]:
housing_df['TotRmsAbvGrd'].unique()

array([ 8,  6,  7,  9,  5, 11,  4, 10, 12,  3,  2, 14], dtype=int64)

In [65]:
housing_df['PoolArea'].isna().sum()

0

In [68]:
housing_df['2ndFlrSF'].unique()

array([ 854,    0,  866,  756, 1053,  566,  983,  752, 1142, 1218,  668,
       1320,  631,  716,  676,  860, 1519,  530,  808,  977, 1330,  833,
        765,  462,  213,  548,  960,  670, 1116,  876,  612, 1031,  881,
        790,  755,  592,  939,  520,  639,  656, 1414,  884,  729, 1523,
        728,  351,  688,  941, 1032,  848,  836,  475,  739, 1151,  448,
        896,  524, 1194,  956, 1070, 1096,  467,  547,  551,  880,  703,
        901,  720,  316, 1518,  704, 1178,  754,  601, 1360,  929,  445,
        564,  882,  920,  518,  817, 1257,  741,  672, 1306,  504, 1304,
       1100,  730,  689,  591,  888, 1020,  828,  700,  842, 1286,  864,
        829, 1092,  709,  844, 1106,  596,  807,  625,  649,  698,  840,
        780,  568,  795,  648,  975,  702, 1242, 1818, 1121,  371,  804,
        325,  809, 1200,  871, 1274, 1347, 1332, 1177, 1080,  695,  167,
        915,  576,  605,  862,  495,  403,  838,  517, 1427,  784,  711,
        468, 1081,  886,  793,  665,  858,  874,  5

In [70]:
housing_df['KitchenAbvGr'].unique()

array([1, 2, 3, 0], dtype=int64)

In [71]:
housing_df['ExterCond'].unique()

array(['TA', 'Gd', 'Fa', 'Po', 'Ex'], dtype=object)

In [72]:
housing_df['SaleCondition'].unique()

array(['Normal', 'Abnorml', 'Partial', 'AdjLand', 'Alloca', 'Family'],
      dtype=object)

In [73]:
housing_df['Utilities'].unique()

array(['AllPub', 'NoSeWa'], dtype=object)

In [82]:
X = housing_df[['ExterCond','SaleCondition','Utilities','GarageArea','LotArea','YearBuilt','OverallCond','OverallQual','FullBath','KitchenAbvGr','BedroomAbvGr','TotRmsAbvGrd','PoolArea','2ndFlrSF','1stFlrSF']]

In [91]:
X.dtypes

ExterCond        object
SaleCondition    object
Utilities        object
GarageArea        int64
LotArea           int64
YearBuilt         int64
OverallCond       int64
OverallQual       int64
FullBath          int64
KitchenAbvGr      int64
BedroomAbvGr      int64
TotRmsAbvGrd      int64
PoolArea          int64
2ndFlrSF          int64
1stFlrSF          int64
dtype: object

In [93]:
X['ExterCond'].unique()

array(['TA', 'Gd', 'Fa', 'Po', 'Ex'], dtype=object)

In [94]:
X['ExterCond'] = X['ExterCond'].map({'TA': 1, 'Gd': 2, 'Fa': 3, 'Po': 4, 'Ex': 5})

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_1348\4213422523.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['ExterCond'] = X['ExterCond'].map({'TA': 1, 'Gd': 2, 'Fa': 3, 'Po': 4, 'Ex': 5})


In [98]:
X['SaleCondition'] = X['SaleCondition'].map({'Normal': 1, 'Abnorml': 2, 'Partial': 3, 'AdjLand': 4, 'Alloca': 5, 'Family': 6})

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_1348\1294793940.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['SaleCondition'] = X['SaleCondition'].map({'Normal': 1, 'Abnorml': 2, 'Partial': 3, 'AdjLand': 4, 'Alloca': 5, 'Family': 6})


In [105]:
X['Utilities'] = X['Utilities'].map({'AllPub': 1, 'NoSeWa': 2})

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_1348\757750583.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Utilities'] = X['Utilities'].map({'AllPub': 1, 'NoSeWa': 2})


In [110]:
X.describe()

ExterCond  SaleCondition    Utilities   GarageArea        LotArea  \
count  1460.000000     1460.00000  1460.000000  1460.000000    1460.000000   
mean      1.148630        1.35000     1.000685   472.980137   10516.828082   
std       0.440222        0.88787     0.026171   213.804841    9981.264932   
min       1.000000        1.00000     1.000000     0.000000    1300.000000   
25%       1.000000        1.00000     1.000000   334.500000    7553.500000   
50%       1.000000        1.00000     1.000000   480.000000    9478.500000   
75%       1.000000        1.00000     1.000000   576.000000   11601.500000   
max       5.000000        6.00000     2.000000  1418.000000  215245.000000   

         YearBuilt  OverallCond  OverallQual     FullBath  KitchenAbvGr  \
count  1460.000000  1460.000000  1460.000000  1460.000000   1460.000000   
mean   1971.267808     5.575342     6.099315     1.565068      1.046575   
std      30.202904     1.112799     1.382997     0.550916      0.220338   
min    1872.000000     1.000000     1.000000     0.000000      0.000000   
25%    1954.000000     5.000000     5.000000     1.000000      1.000000   
50%    1973.000000     5.000000     6.000000     2.000000      1.000000   
75%    2000.000000     6.000000     7.000000     2.000000      1.000000   
max    2010.000000     9.000000    10.000000     3.000000      3.000000   

       BedroomAbvGr  TotRmsAbvGrd     PoolArea     2ndFlrSF     1stFlrSF  
count   1460.000000   1460.000000  1460.000000  1460.000000  1460.000000  
mean       2.866438      6.517808     2.758904   346.992466  1162.626712  
std        0.815778      1.625393    40.177307   436.528436   386.587738  
min        0.000000      2.000000     0.000000     0.000000   334.000000  
25%        2.000000      5.000000     0.000000     0.000000   882.000000  
50%        3.000000      6.000000     0.000000     0.000000  1087.000000  
75%        3.000000      7.000000     0.000000   728.000000  1391.250000  
max        8.000000     14.000000   738.000000  2065.000000  4692.000000

## Definición de Y

In [108]:
y = housing_df['SalePrice']

***

## Predición - utilizando DecisionTreeClassifier

In [111]:
from sklearn.model_selection import train_test_split

In [112]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [118]:
len(X_train)

1168

In [119]:
len(X_test)

292

In [120]:
from sklearn import tree
modelo = tree.DecisionTreeClassifier()

In [121]:
modelo.fit(X_train,y_train)

DecisionTreeClassifier()

In [122]:
modelo.score(X_train,y_train)

0.9965753424657534

In [124]:
from sklearn.metrics import confusion_matrix
# Se establece predicción sobre el 'Test'
y_predict = modelo.predict(X_test)
confmatrix = confusion_matrix(y_predict,y_test)
confmatrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)